version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql_jit
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3308:3306'
    volumes:
      - jit:/var/lib/mysql

volumes:
  jit:


